// global
export const API_ROOT = 'http://localhost:8080/api';
export const POSSIBLE_EXCHANGES = ['Binance', 'Bitfinex', 'GDAX', 'Cryptopia'];

export const API_USER_EXCHANGE_KEYS = `${API_ROOT}/user/exchange-keys`;

// actions
export const USER_SET_AUTH = 'USER_SET_AUTH';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const DESTORY_USER_SIGNUP_SUCCESS = 'DESTORY_USER_SIGNUP_SUCCESS';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_ERROR = 'USER_DATA_ERROR';


export const PROMISE_EXCHANGE_LOADING = 'PROMISE_EXCHANGE_LOADING';
export const PROMISE_EXCHANGE_SUCCESS = 'PROMISE_EXCHANGE_SUCCESS';
export const PROMISE_EXCHANGE_ERROR = 'PROMISE_EXCHANGE_ERROR';


export const TOGGLE_SUBSCRIPTION_MODAL = 'TOGGLE_SUBSCRIPTION_MODAL';
